---
- name: Add tools for building code
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install make and gcc from apt
      ansible.builtin.apt:
        pkg:
          - make
          - gcc
        state: present

    - name: Install go language from snap
      community.general.snap:
        name: go
        classic: yes
        state: present

- name: Configure docker for devel user
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install docker.io from apt
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Add "{{ devel_user }}" to docker group
      ansible.builtin.user:
        name: "{{ devel_user }}"
        groups: docker
        append: yes

- name: Add Kubernetes related tools
  hosts: all

  tasks:
    - name: Make local bin directory
      ansible.builtin.file:
        path: "/home/{{ devel_user }}/bin"
        state: directory
        mode: "0755"

    - name: Get kubectl version
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: kubectl_version

    - name: "Download version {{ kubectl_version.content }} kubectl"
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
        dest: "/home/{{ devel_user }}/bin/kubectl"
        mode: u+x

    - name: Get GOOS setting
      ansible.builtin.shell: go env GOOS
      register: go_goos

    - name: Get GOARCH setting
      ansible.builtin.shell: go env GOARCH
      register: go_goarch

    - name: Download latest kubebuilder
      ansible.builtin.get_url:
        url: "https://go.kubebuilder.io/dl/latest/{{ go_goos.stdout }}/{{ go_goarch.stdout }}"
        dest: "/home/{{ devel_user }}/bin/kubebuilder"
        mode: u+x
