---
- name: Add tools for building code
  hosts: all
  remote_user: root

  tasks:
    - name: Install make and gcc from apt
      ansible.builtin.apt:
        pkg:
          - make
          - gcc
        state: present
    - name: Install go language from snap
      community.general.snap:
        name: go
        classic: yes
        state: present

